<?php
/**
 * @file
 * cove_chronologies_timelines.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cove_chronologies_timelines_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'body'.
  $field_bases['body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(
      0 => 'node',
    ),
    'field_name' => 'body',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'profile2_private' => FALSE,
    ),
    'translatable' => 1,
    'type' => 'text_with_summary',
  );

  // Exported field_base: 'field_assoc_places'.
  $field_bases['field_assoc_places'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_assoc_places',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'place' => 'place',
        ),
      ),
      'sync' => 'field_assoc_events',
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_event2'.
  $field_bases['field_event2'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_event2',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'profile2_private' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_event_date'.
  $field_bases['field_event_date'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_event_date',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'timestamp' => array(
        0 => 'timestamp',
      ),
      'timestamp_to' => array(
        0 => 'timestamp_to',
      ),
    ),
    'locked' => 0,
    'module' => 'partial_date',
    'settings' => array(
      'estimates' => array(
        'day' => array(
          '0|12' => 'The start of the month',
          '10|20' => 'The middle of the month',
          '18|31' => 'The end of the month',
        ),
        'hour' => array(
          '0|1' => 'Midnight',
          '6|12' => 'Morning',
          '6|18' => 'Day time',
          '12|13' => 'Noon',
          '12|18' => 'Afternoon',
          '18|6' => 'Night',
          '18|22' => 'Evening',
        ),
        'minute' => array(),
        'month' => array(
          '2|4' => 'Spring',
          '5|7' => 'Summer',
          '8|10' => 'Autumn',
          '11|1' => 'Winter',
        ),
        'second' => array(),
        'year' => array(
          '-60000|1600' => 'Pre-colonial',
          '1500|1599' => '16th century',
          '1600|1699' => '17th century',
          '1700|1799' => '18th century',
          '1800|1899' => '19th century',
          '1900|1999' => '20th century',
          '2000|2099' => '21st century',
        ),
      ),
      'minimum_components' => array(
        'from_estimates_day' => 0,
        'from_estimates_hour' => 0,
        'from_estimates_minute' => 0,
        'from_estimates_month' => 0,
        'from_estimates_second' => 0,
        'from_estimates_year' => 0,
        'from_granularity_day' => 0,
        'from_granularity_hour' => 0,
        'from_granularity_minute' => 0,
        'from_granularity_month' => 0,
        'from_granularity_second' => 0,
        'from_granularity_timezone' => 0,
        'from_granularity_year' => 1,
        'to_estimates_day' => 0,
        'to_estimates_hour' => 0,
        'to_estimates_minute' => 0,
        'to_estimates_month' => 0,
        'to_estimates_second' => 0,
        'to_estimates_year' => 0,
        'to_granularity_day' => 0,
        'to_granularity_hour' => 0,
        'to_granularity_minute' => 0,
        'to_granularity_month' => 0,
        'to_granularity_second' => 0,
        'to_granularity_timezone' => 0,
        'to_granularity_year' => 0,
        'txt_long' => 0,
        'txt_short' => 0,
      ),
    ),
    'translatable' => 0,
    'type' => 'partial_date_range',
  );

  // Exported field_base: 'field_event_source'.
  $field_bases['field_event_source'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_event_source',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'event_source',
          'parent' => 0,
        ),
      ),
      'options_list_callback' => 'content_taxonomy_allowed_values',
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'field_image'.
  $field_bases['field_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_image',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  // Exported field_base: 'field_items_in_this_chronology'.
  $field_bases['field_items_in_this_chronology'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_items_in_this_chronology',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'chronology_entry' => 'chronology_entry',
        ),
      ),
      'sync' => 'field_parent_chronology',
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_parent_chronology'.
  $field_bases['field_parent_chronology'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_parent_chronology',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'chronology' => 'chronology',
        ),
      ),
      'sync' => 'field_items_in_this_chronology',
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_resource_index'.
  $field_bases['field_resource_index'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_resource_index',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'direction' => 'ASC',
          'property' => 'title',
          'type' => 'property',
        ),
        'target_bundles' => array(
          'editions_index_page' => 'editions_index_page',
        ),
      ),
      'handler_submit' => 'Change handler',
      'profile2_private' => FALSE,
      'sync' => 'field_documents_in_this_edition',
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'og_group_ref'.
  $field_bases['og_group_ref'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'og_group_ref',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'og',
      'handler_settings' => array(
        'behaviors' => array(
          'og_behavior' => array(
            'status' => TRUE,
          ),
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'membership_type' => 'og_membership_type_default',
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'course' => 'course',
        ),
      ),
      'handler_submit' => 'Change handler',
      'sync' => '',
      'target_type' => 'node',
    ),
    'target_type' => 'node',
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
