<?php
// Init, cram path into js var
function annotationViewer_init() {
	drupal_add_js(array('annotationViewer' => array('basepath' => drupal_get_path('module', 'annotationViewer'))), 'setting');
}

function annotationViewer_preprocess_page(&$vars) {
  // FIXME: This should eventually be removed, it's used in only one spot (line 299 in view_annotator.js)
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/jquery-dateFormat/1.0/jquery.dateFormat.min.js', 'external');
}
